### ISSUE TITLE
Error running test.m

### ISSUE THREAD

**Issue by Cartucho** [cvlab-epfl/diff-nrsfm#2]
Hello I tried running the `test.m` directly and got the following error: 

```
Error using optimoptions (line 124)
Invalid solver specified. Provide a solver name or handle (such as 'fmincon' or @fminunc).
Type DOC OPTIMOPTIONS for a list of solvers.

Error in test (line 43)
options =
optimoptions(@lsqnonlin,'Algorithm','levenberg-marquardt','Display','off','UseParallel',true,'MaxIterations',2000,'FunctionTolerance',1e-10); 
```

Should I set up anything before or it should work right off-the-shelf? Or does it require a specific version of Matlab?

EDIT: I think it has to do with the `Optimization Toolbox` not being installed on my computer which is required to run that function, I will give it a try.

EDIT EDIT: Installing the `Optimization Toolbox` solved the error!

**Comment by Cartucho** [comment]
Now I am getting the following error:

```
Unrecognized function or variable 'bbs_create'.

Error in calculate_depth (line 10)
        bbsd = bbs_create(umin, umax, nC, vmin, vmax, nC, 1);

Error in recover_surfaces (line 24)
P_grid=calculate_depth(N_res,u_all,v_all,1e0);

Error in test (line 46)
[P_d,N_d,err_pd,err_nd] = recover_surfaces(k1_opt,k2_opt,num,a,b,c,d,u1,v1,u,v,I1u,I2u,I1v,I2v,idx,qgth,Pgth,Ngth);
```

Again, I will check if there are any other Toolboxes required for using these functions.

**Comment by shaifaliparashar** [comment]
As per the readme file, you need to download the bbs toolbox:
http://www.brnt.eu/downloads.php#bbs
Best,
Shaifali

**Comment by shaifaliparashar** [comment]
I would suggest to download the pre-complied version for windows/linux
It is difficult to use this toolbox on mac.

**Comment by Cartucho** [comment]
Thank you, I had the BBS folder already since I cloned your entire Github repository. I needed to add it to the matlab path:

![image](https://user-images.githubusercontent.com/15831541/114531933-41c3eb00-9c44-11eb-84bb-cb4d46d9fd74.png)

**Comment by Cartucho** [comment]
Adding to the path worked:

![image](https://user-images.githubusercontent.com/15831541/114556543-bad13b80-9c60-11eb-9457-46dccb221222.png)

I was wondering if I was supposed to see something after running the code?
